[package]
org = "ballerinax"
name = "rabbitmq"
version = "2.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "./lib/amqp-client-5.10.0.jar"

[[platform.java11.dependency]]
path = "../native/build/libs/rabbitmq-native-2.0.0.jar"

[build-options]
observabilityIncluded=true
