[package]
org = "ballerinax"
name = "rabbitmq"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "./lib/amqp-client-@amqp.client.version@.jar"

[[platform.java11.dependency]]
path = "../native/build/libs/rabbitmq-native-@project.version@.jar"

[build-options]
observabilityIncluded=true
