[package]
org = "ballerinax"
name = "rabbitmq"
version = "2.4.0"
authors = ["Ballerina"]
keywords = ["service", "client", "messaging", "network", "pubsub"]
repository = "https://github.com/ballerina-platform/module-ballerinax-rabbitmq"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.1.0"

[[platform.java11.dependency]]
path = "./lib/amqp-client-5.10.0.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "rabbitmq-native"
version = "2.4.0"
path = "../native/build/libs/rabbitmq-native-2.4.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.0.0"
path = "./lib/constraint-native-1.0.0-20220718-173500-74bf392.jar"

[build-options]
observabilityIncluded=true
