[package]
org = "ballerinax"
name = "rabbitmq"
version = "2.0.1"
authors = ["Ballerina"]
keywords = ["service", "client", "messaging", "network", "pubsub"]
repository = "https://github.com/ballerina-platform/module-ballerinax-rabbitmq"
license = ["Apache-2.0"]
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "./lib/amqp-client-5.10.0.jar"

[[platform.java11.dependency]]
path = "../native/build/libs/rabbitmq-native-2.0.1-SNAPSHOT.jar"

[build-options]
observabilityIncluded=true
