[consolidatorService.config]

# RabbitMQ queue which will get notified for websub topic registration/deregistration
# All the hubs must be pointed to the same RabbitMQ queue to notify websub topic registration/deregistration
REGISTERED_WEBSUB_TOPICS_QUEUE = "registered-websub-topics"

# RabbitMQ queue which stores consolidated websub topics for the hub
CONSOLIDATED_WEBSUB_TOPICS_QUEUE = "consolidated-websub-topics"

# RabbitMQ queue which will get notified for websub subscription/unsubscription
# All the hubs must be pointed to the same RabbitMQ queue to notify websub subscription/unsubscription
WEBSUB_SUBSCRIBERS_QUEUE = "registered-websub-subscribers"

# RabbitMQ queue which is stores consolidated websub subscribers for this server
CONSOLIDATED_WEBSUB_SUBSCRIBERS_QUEUE = "consolidated-websub-subscribers"
