[project]
org-name = "ballerinax"
version = "@toml.version@"

[dependencies]
"ballerina/crypto" = "@stdlib.crypto.version@"
"ballerina/log" = "@stdlib.log.version@"
"ballerina/time" = "@stdlib.time.version@"
"ballerina/system" = "@stdlib.system.version@"
"ballerina/runtime" = "@stdlib.runtime.version@"
"ballerina/io" = "@stdlib.io.version@"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "amqp-client"
    version = "5.7.3"
    path = "./lib/amqp-client-5.7.3.jar"
    groupId = "com.rabbitmq"
    modules = ["rabbitmq"]

    [[platform.libraries]]
    artifactId = "rabbitmq"
    version = "@project.version@"
    path = "../rabbitmq-native/build/libs/rabbitmq-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["rabbitmq"]
