[package]
org = "ballerinax"
name = "rabbitmq"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "log"
version = "@stdlib.log.version@"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "@stdlib.crypto.version@"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "@stdlib.uuid.version@"

[[platform.java11.dependency]]
path = "./lib/amqp-client-@amqp.client.version@.jar"
groupId = "com.rabbitmq"
artifactId = "amqp-client"
version = "@amqp.client.version@"

[[platform.java11.dependency]]
path = "../rabbitmq-native/build/libs/rabbitmq-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "rabbitmq"
version = "@project.version@"
