[package]
org = "ballerinax"
name = "rabbitmq"
version = "@toml.version@"

[[dependency]]
org = "ballerina"
name = "runtime"
version = "@stdlib.runtime.version@"

[[dependency]]
org = "ballerina"
name = "log"
version = "@stdlib.log.version@"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "@stdlib.crypto.version@"

[[dependency]]
org = "ballerina"
name = "system"
version = "@stdlib.system.version@"

[[platform.java11.dependency]]
path = "./lib/amqp-client-5.10.0.jar"
groupId = "com.rabbitmq"
artifactId = "amqp-client"
version = "5.10.0"

[[platform.java11.dependency]]
path = "../rabbitmq-native/build/libs/rabbitmq-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "rabbitmq"
version = "@project.version@"
