[project]
org-name = "ballerinax"
version = "@toml.version@"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "amqp-client"
    version = "5.7.3"
    path = "./lib/amqp-client-5.7.3.jar"
    groupId = "com.rabbitmq"
    modules = ["rabbitmq"]

    [[platform.libraries]]
    artifactId = "rabbitmq"
    version = "@project.version@"
    path = "../rabbitmq-native/build/libs/rabbitmq-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["rabbitmq"]
