[package]
org = "ballerinax"
name = "rabbitmq"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "./lib/amqp-client-@amqp.client.version@.jar"
groupId = "com.rabbitmq"
artifactId = "amqp-client"
version = "@amqp.client.version@"

[[platform.java11.dependency]]
path = "../rabbitmq-native/build/libs/rabbitmq-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "rabbitmq"
version = "@project.version@"
